# Generated by Django 3.2.8 on 2021-12-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_id', models.TextField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
