# Generated by Django 3.2.8 on 2021-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('date', models.CharField(db_column='date', max_length=20)),
                ('home_team', models.CharField(db_column='home', max_length=10)),
                ('away_team', models.CharField(db_column='away', max_length=10)),
                ('home_score', models.CharField(db_column='home_score', max_length=10)),
                ('away_score', models.CharField(db_column='away_score', max_length=10)),
                ('location', models.CharField(db_column='stadium', max_length=15)),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('team', models.CharField(db_column='team', max_length=20)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('backNum', models.CharField(db_column='backNum', max_length=20)),
                ('birth', models.CharField(db_column='birth', max_length=20)),
                ('position', models.CharField(db_column='position', max_length=30)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Starting_lineup',
            fields=[
                ('lineup_id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('date', models.CharField(db_column='date', max_length=20, null=True)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('team', models.CharField(db_column='team', max_length=20)),
                ('position', models.CharField(db_column='position', max_length=20)),
                ('order', models.IntegerField(db_column='order', default=0)),
            ],
            options={
                'db_table': 'starting_lineup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='team_name', max_length=10)),
                ('team_img', models.CharField(db_column='team_img', max_length=100)),
                ('team_stadium', models.CharField(db_column='team_stadium', max_length=10)),
                ('team_code', models.CharField(db_column='team_code', max_length=5)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
