# Generated by Django 3.2.8 on 2021-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20211127_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitter_stats',
            fields=[
                ('stat_id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('team', models.CharField(db_column='team', max_length=20)),
                ('opposite_team', models.CharField(db_column='oppositeTeam', max_length=20)),
                ('game', models.CharField(db_column='game', max_length=20)),
                ('pa', models.CharField(db_column='pa', max_length=20)),
                ('ab', models.CharField(db_column='ab', max_length=20)),
                ('h', models.CharField(db_column='h', max_length=20)),
                ('oneb', models.CharField(db_column='1b', max_length=20)),
                ('twob', models.CharField(db_column='2b', max_length=20)),
                ('threeb', models.CharField(db_column='3b', max_length=20)),
                ('hr', models.CharField(db_column='hr', max_length=20)),
                ('r', models.CharField(db_column='r', max_length=20)),
                ('rbi', models.CharField(db_column='rbi', max_length=20)),
                ('bb', models.CharField(db_column='bb', max_length=20)),
                ('ibb', models.CharField(db_column='ibb', max_length=20)),
                ('hbp', models.CharField(db_column='hbp', max_length=20)),
                ('k', models.CharField(db_column='k', max_length=20)),
                ('sf', models.CharField(db_column='sf', max_length=20)),
                ('sh', models.CharField(db_column='sh', max_length=20)),
                ('gidp', models.CharField(db_column='gidp', max_length=20)),
                ('sb', models.CharField(db_column='sb', max_length=20)),
                ('cs', models.CharField(db_column='cs', max_length=20)),
                ('avg', models.CharField(db_column='avg', max_length=20)),
            ],
            options={
                'db_table': 'hitter_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitcher_stats',
            fields=[
                ('stat_id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('team', models.CharField(db_column='team', max_length=20)),
                ('opposite_team', models.CharField(db_column='oppositeTeam', max_length=20)),
                ('w', models.CharField(db_column='w', max_length=20)),
                ('l', models.CharField(db_column='l', max_length=20)),
                ('save', models.CharField(db_column='save', max_length=20)),
                ('hld', models.CharField(db_column='hld', max_length=20)),
                ('blown', models.CharField(db_column='blown', max_length=20)),
                ('game', models.CharField(db_column='game', max_length=20)),
                ('gs', models.CharField(db_column='gs', max_length=20)),
                ('ip', models.CharField(db_column='ip', max_length=20)),
                ('k', models.CharField(db_column='k', max_length=20)),
                ('bb', models.CharField(db_column='bb', max_length=20)),
                ('hr', models.CharField(db_column='hr', max_length=20)),
                ('babip', models.CharField(db_column='babip', max_length=20)),
                ('lob', models.CharField(db_column='lob', max_length=20)),
                ('era', models.CharField(db_column='era', max_length=20)),
                ('ra', models.CharField(db_column='ra', max_length=20)),
                ('fip', models.CharField(db_column='fip', max_length=20)),
                ('kfip', models.CharField(db_column='kfip', max_length=20)),
                ('war', models.CharField(db_column='war', max_length=20)),
            ],
            options={
                'db_table': 'pitcher_stats',
                'managed': False,
            },
        ),
    ]
