# Generated by Django 3.2.8 on 2021-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='url', max_length=500)),
                ('team', models.CharField(db_column='team', max_length=10)),
                ('date', models.CharField(db_column='date', max_length=10)),
                ('time', models.CharField(db_column='time', max_length=50)),
                ('publisher', models.CharField(db_column='publisher', max_length=50)),
                ('journalist', models.CharField(db_column='journalist', max_length=50)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('content', models.CharField(db_column='content', max_length=5000)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
    ]
